### ISSUE TITLE
Add example description

### ISSUE THREAD

**Issue by shushu789** [haga-rak/fluxzy.core#195]
Hi, can you give me a simple example of how to get the http/https traffic from a browser or any other device within the LAN? Just like the fluxzy desktop version, you can get the URL and other details of the request and response. I have read the documentation and API you provided, but since I don’t know much English, I can only use translation. I don’t understand many places, so I am particularly Came here to ask for help, I saw this example in the documentation but not how to get the requested URLs and the response information associated with them:
# Deflect OS traffic
Fluxy.Core provides APIs to automatically deflects OS traffic to itself. This feature is only available on Desktop environment (Windows, macOS and Gnome based Linux).

The static method SystemProxyRegistrationHelper.Create is the entry point to enable this feature. It takes endpoints returned by Proxy.Start() as argument and register the first available endpoint as the system proxy. The call returns an IAsyncDisposable that can be used to revert the system proxy to its previous state.

```
using Fluxzy;
using Fluxzy.Core;

// Create a new proxy instance 
await using var proxy = new Proxy(FluxzySetting.CreateDefault());

// Proxy run will returns the endpoints that the proxy is listening on
var endPoints = proxy.Run();

// Pick an endpoint and register it as the system proxy
var proxyRegistration = await SystemProxyRegistrationHelper.Create(endPoints.First());

// System proxy is now set 

// Call DisposeAsync() to unregister the proxy
await proxyRegistration.DisposeAsync();
```

My purpose is to implement a very simple tool similar to the desktop version in my WPF, which can display the URL list of http/https requests and responses of all programs that use proxies, as well as the body of the response. Thank you for your hard work. Got it

**Comment by shushu789** [comment]
Thank you for the help, but when I try to read the decoded response body, I often encounter the following two common errors:

### Error 1:

```
System.IO.IOException: Error while reading chunked stream: EOF was reached on chunked stream before reading a valid length block.
   at Fluxzy.Misc.Streams.ChunkedTransferReadStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
   at Fluxzy.Misc.Streams.ChunkedTransferReadStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at Fluxzy.Misc.Streams.CombinedReadonlyStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken token)
   at Program.<<Main>$>g__GetBody|0_1(DirectoryArchiveReader archiveReader, Int32 exchangeId) in 
```

### Error 2:

```
System.IO.IOException: Error while reading chunked stream: Chunk size is larger than 40.
   at Fluxzy.Misc.Streams.ChunkedTransferReadStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
   at System.IO.Compression.DeflateStream.<ReadAsyncMemory>g__Core|51_0(Memory`1 buffer, CancellationToken cancellationToken)
   at Fluxzy.Misc.Streams.CombinedReadonlyStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken token)
```

### I read these two objects for reading (ChunkedTransferreadStream or CombinedReadonlystream):

```csharp
using (var responseBodyStream = archiveReader.GetDecodedResponseBody(exchangeId))
{
    if (responseBodyStream != null)
    {
        var chunkedStream = new CombinedReadonlyStream(true, responseBodyStream);
        // var chunkedStream = new ChunkedTransferReadStream(responseBodyStream,true);


        var buffer = new Memory<byte>(new byte[8192]); // Buffer for reading data
        StringBuilder stringBuilder = new StringBuilder(); // Stores the read text

        while (true)
        {
            var bytesRead = await chunkedStream.ReadAsync(buffer);
            if (bytesRead == 0) break; 
            var text = Encoding.UTF8.GetString(buffer.Span.Slice(0, bytesRead));
            stringBuilder.Append(text);
        }
}
```

For smaller response bodies, they can usually be read directly without throwing exceptions. I primarily read the response body of specific URLs, which are usually JSON data.

Do you have any good suggestions? I've tried various methods, including using the original StreamReader, but to no avail.
